site_name: TkModLab
site_url: http://desy-fh-elab.github.io/cmstkmodlab
site_description: Documentation for DESY FH-E-Lab Software
site_author: Andreas Mussgiller

repo_url: https://github.com/DESY-FH-ELab/cmstkmodlab

pages:
- Home: index.md
- Build:
    - configure: build/configure.md
    - Ubuntu Linux: build/UbuntuLinux.md
    - Raspbian Linux: build/RaspbianLinux.md
    - OSX El Capitan: build/OSXElCapitan.md
- Thermo:
    - thermoDAQ: thermo/thermoDAQ.md
- Defo:
    - defoDAQ: defo/defoDAQ.md
    - defoDAQ Scripting: defo/defoDAQScripting.md
- Assembly: index.md

theme: flatly
